config/routes.rb
TheGoodReads::Application.routes.draw do
  resources :books
  resources :users
  resources :user_books
  resources :user_sessions, only: [:create, :destroy]

  delete '/sign_out', to: 'user_sessions#destroy', as: :sign_out
  get '/sign_in', to: 'user_sessions#new', as: :sign_in
  root "pages#home"
  match '/my_books',    to: 'pages#my_books',    via: 'get'
  match '/pages/users',    to: 'pages#users',    via: 'get'
  match '/pages/books',    to: 'pages#books',    via: 'get'
  match 'delete_user',to: 'users#destroy', via: 'delete'
  match '/books/id' ,to: 'books#destroy', via: "delete"
  

end

app/models/book.rb
class Book < ActiveRecord::Base

has_many :user_books
has_many :users , through: :user_books
end

app/models/user.rb
class User < ActiveRecord::Base
has_many :user_books
has_many :books , through: :user_books
acts_as_authentic do |c|
  c.crypto_provider = Authlogic::CryptoProviders::Sha512
end

end
class User
  self.per_page = 10
end

# set per_page globally
WillPaginate.per_page = 10

app/models/user_book.rb
class UserBook < ActiveRecord::Base
belongs_to :user
belongs_to :book
end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  @usar = @c_user
private

def current_user_session
  return @current_user_session if defined?(@current_user_session)
  @current_user_session = UserSession.find
end

def current_user
  return @current_user if defined?(@current_user)
  @current_user = current_user_session && current_user_session.user
end
def usar
	User.first
end
helper_method :current_user_session, :current_user , :usar
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
def new
	@book = Book.new
end
def destroy
    Book.find(params[:id]).destroy
    flash[:success] = "Book Deleted"
    redirect_to pages_books_path
  end
  def create
    @book = Book.create(book_params)
    
      flash[:success] = "Book Created"
      redirect_to pages_books_path
    
  end
def index
    @users = Post.paginate(:page => params[:page], :per_page => 5)

	@book = Book.all.find(params[:id])
end



private
byebug
def book_params
  byebug
    params.require(:book).permit(:title, :author, :summary)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home

  @books = Book.all 
  end


  def my_books
  end
  def index
  end

  def users
    byebug
    @users = User.all
  end
  def books
    byebug
    @books = Book.all
  end
end 

app/controllers/user_books_controller.rb
class UserBooksController < ApplicationController

def new
@user_book = UserBook.new
end

def create
    byebug
    @user_book = UserBook.create(:user_id => params[:user_id],:book_id => params[:book_id])
      flash[:success] = "Book Created"
      redirect_to pages_books_path
end

def destroy
	
	 UserBook.find(params[:id]).destroy
	flash[:success] = "Book Removed"
	redirect_to pages_books_path
end
def index
	end

end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  def new
    @user_session = UserSession.new
  end

  def create
    @user_session = UserSession.new(user_session_params)
    if @user_session.save
      flash[:success] = "Welcome back!"
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    current_user_session.destroy
    flash[:success] = "Goodbye!"
    redirect_to root_path
  end

  private

  def user_session_params
    params.require(:user_session).permit(:email, :password, :remember_me)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

   def create
    @user = User.new(users_params)
    # @user.password = 'helloasdasdasdsa'
    byebug
    if @user.save
      flash[:success] = "Account registered!"
      redirect_to root_path
    else
      render :new
    end
  end
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to pages_users_path
  end
  def index
    @users = User.all? 
  end
  private

  def users_params
    byebug
    params.require(:user).permit(:name,:email, :password,:password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/user_books_helper.rb
module UserBooksHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/new.html.erb
<div class="page-header"><h1>Create</h1></div>

<%= form_for @book do |f| %>
  

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title%>
  </div>

  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author%>
  </div>

  

  <div class="form-group">
    <%= f.label :summary %>
    <%= f.text_area :summary, size: "60x12" %>
  </div>

  <%= f.submit 'Create', class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/books/show.html.erb
<% book = @book %>
<li>
  <%= book.title %>
  <%= book.author %>
  <%= book.summary%>
 <li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TheGoodReads</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<nav class="navbar navbar-light bg-light">
  
  <form class="form-inline">
    <a class="btn btn-outline-primary" href="/" role="button">
    HOME
    </a>
    <div style="padding-left: 10px;">
      <a class="btn btn-outline-success" href="/my_books" role="button">
      MY BOOKS
      </a>
       
     <ul class="nav navbar-nav pull-right">
        <% if current_user %>
          <li><span><%= current_user.email %></span></li>
          <li><%= link_to 'Sign Out', sign_out_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Sign In', sign_in_path %></li>
        <% end %>
      </ul>
     </div>
  </form>
</nav>

<%= yield %>

</body>
</html>

app/views/pages/books.html.erb
<h1>All Books</h1>
<% if (current_user && current_user.admin? ) %>
<%= link_to "Create Book", new_book_path, class: "btn btn-lg btn-primary" %>
<%end%>
<ul>
	 <% @books.each do |book| %>
	 <ul>
	 	<li> <%= book.title %> </li>
	 	<li> <%= book.author %> </li>
	 	<li> <%= book.summary%> </li>
	 	<% if (current_user && current_user.admin? ) %>
	 	<%= link_to "delete", book , method: :delete,
                                  data: { confirm: "You sure?" } %>
        <%end%>
        <% if !(current_user.books.include?book) %>
         <%= link_to "Add Book To My Books", {:controller => "user_books", :action => "create", :user_id => current_user.id, :book_id=> book.id }, {:method=>:post}  %>
         <%else%>
        <% @current_user_book =UserBook.find_by_user_id_and_book_id(current_user.id,book.id) %>
         <%= link_to "Remove Book From My Books", @current_user_book, method: :delete,
                                  data: { confirm: "You sure?" } %>
         <%end%>
     </ul>
     <%end%>
 </ul>
 

app/views/pages/home.html.erb
 <%= link_to "List Users", "pages/users", class: "btn btn-lg btn-primary" %>
 <br>
 <%= link_to "List Books", "pages/books", class: "btn btn-lg btn-primary" %>

app/views/pages/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome!</h1>
    <p>Sign up to get started.</p>
    <p>
      <%= link_to new_user_path, class: 'btn btn-primary btn-lg' do %>
        Sign Up &raquo;
      <% end %>
    </p>
  </div>
</div>

app/views/pages/my_books.html.erb
<h1>My Books</h1>
<%if current_user.books == [] %>
<h3>Sorry You Dont Have Any Books In Your Shelf</h3>
<%else%>
<% current_user.books.each do |book| %>
    <li>
        <%= book.title %> <br>
        <%= book.author %> <br>
        <%= book.summary %> <br>
        
    </li>
   <% end %>
  <%end%>

app/views/pages/users.html.erb
<h1>All Users</h1>
<ul>
	 <% @users.each do |user| %>
	 <ul>

	 	<li> <%= user.name %> </li>
	 	<li> <%= user.email %> </li>
	 	<% if (current_user && current_user.admin? && !(current_user==(user))) %>
	 	<%= link_to "delete", user, method: :delete,
                                  data: { confirm: "You sure?" } %>
        </a> </li>
        <%end%>
        </ul>
      <%end%> 
 </ul>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <div class="panel panel-warning errors">
    <div class="panel-heading">
      <h5><i class="glyphicon glyphicon-exclamation-sign"></i> Found errors while saving</h5>
    </div>

    <ul class="panel-body">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/user_sessions/new.html.erb
<div class="page-header"><h1>Sign In</h1></div>

<%= form_for @user_session do |f| %>
  <%= render 'shared/errors', object: @user_session %>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :remember_me %>
    <%= f.check_box :remember_me %>
  </div>

  <%= f.submit "Log in!", class: 'btn btn-primary btn-lg' %>
<% end %>

app/views/users/new.html.erb
<div class="page-header"><h1>Register</h1></div>

<%= form_for @user do |f| %>
  <%= render 'shared/errors', object: @user %> 

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name%>
  </div>

  <div class="form-group">
    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password %>
    <%= f.password_field :password, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation, class: 'form-control' %>
  </div>

  <%= f.submit 'Register', class: 'btn btn-primary btn-lg' %>
<% end %>